export type ColumnMeta = {
  description: string;
};

export type TableMeta = {
  description: string;
  columns: Record<string, ColumnMeta>;
  createSql?: string;
  alterSql?: string;
};

export const TABLES_META: Record<string, TableMeta> = {
  salaries: {
    description: 'Salary grade master table',
    columns: {
      id: { description: 'Primary key' },
      grades: { description: 'Employee grade (e.g. Grade A)' },
      category: {
        description: 'Employee category (White Collar or Blue Collar)',
      },
      role: { description: 'Employee role/designation (e.g. Site Engineer)' },
      expInYears: { description: 'Experience range (e.g. 2-4, 5-7, 15+)' },
      monthlySalary: { description: 'Monthly salary amount' },
      avgCostPerHr: { description: 'Average cost per hour' },
      bookingCost: { description: 'Booking cost' },
      isDeleted: { description: 'Soft delete flag' },
      createdAt: { description: 'Record creation timestamp' },
      updatedAt: { description: 'Record update timestamp' },
    },
    createSql: `CREATE TABLE salaries (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  grades          VARCHAR NOT NULL,
  category        VARCHAR NOT NULL DEFAULT '',
  role            VARCHAR NOT NULL DEFAULT '',
  "expInYears"    VARCHAR NOT NULL,
  "monthlySalary" DECIMAL(12,2) NOT NULL,
  "avgCostPerHr"  DECIMAL(10,2) NOT NULL,
  "bookingCost"   DECIMAL(12,2) NOT NULL,
  "isDeleted"     BOOLEAN NOT NULL DEFAULT false,
  "createdAt"     TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"     TIMESTAMP NOT NULL DEFAULT now()
);`,
  },
  users: {
    description: 'All users',
    columns: {
      id: { description: 'Primary key' },
      name: { description: 'User full name' },
      email: { description: 'Login email (unique)' },
      username: { description: 'Login username (unique)' },
      employeeId: { description: 'Employee ID' },
      phone: { description: 'Phone number' },
      address: { description: 'Address' },
      passwordHash: { description: 'Bcrypt password hash' },
      role: { description: 'User role (admin, site_engineer, accounts_manager, purchase_team, viewer)' },
      isActive: { description: 'Account active status' },
      salaryGradeId: { description: 'FK to salaries.id' },
      createdAt: { description: 'Record creation timestamp' },
      updatedAt: { description: 'Record update timestamp' },
    },
    alterSql: `-- Add salaryGradeId column if missing on existing users table:
ALTER TABLE users
  ADD COLUMN "salaryGradeId" UUID NULL,
  ADD CONSTRAINT fk_users_salary_grade FOREIGN KEY ("salaryGradeId") REFERENCES salaries(id);`,
    createSql: `CREATE TABLE users (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name            VARCHAR NOT NULL,
  email           VARCHAR NOT NULL UNIQUE,
  username        VARCHAR UNIQUE,
  "employeeId"    VARCHAR,
  phone           VARCHAR,
  address         TEXT,
  "passwordHash"  VARCHAR NOT NULL,
  role            VARCHAR NOT NULL DEFAULT 'viewer',
  "isActive"      BOOLEAN NOT NULL DEFAULT true,
  "salaryGradeId" UUID REFERENCES salaries(id),
  "createdAt"     TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"     TIMESTAMP NOT NULL DEFAULT now()
);`,
  },
  weekly_timesheets: {
    description: 'Weekly timesheet header (one per engineer per week)',
    columns: {
      id: { description: 'Primary key' },
      siteEngineerId: { description: 'FK to users.id (ManyToOne -> User)' },
      weekStart: { description: 'Week start Monday' },
      weekEnd: { description: 'Week end Sunday' },
      totalHours: { description: 'Total hours' },
      status: { description: 'draft/submitted/approved/rejected' },
      approvedById: { description: 'FK to users.id (who verified/approved)' },
      approvedAt: { description: 'Verification/approval timestamp' },
      isDeleted: { description: 'Soft delete' },
      createdAt: { description: '' },
      updatedAt: { description: '' },
    },
    createSql: `CREATE TABLE weekly_timesheets (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "siteEngineerId" UUID NOT NULL REFERENCES users(id),
  "weekStart"      DATE NOT NULL,
  "weekEnd"        DATE NOT NULL,
  "totalHours"     DECIMAL(10,2) NOT NULL DEFAULT 0,
  status           VARCHAR NOT NULL DEFAULT 'draft',
  "approvedById"   VARCHAR NULL,
  "approvedAt"     DATE NULL,
  "isDeleted"      BOOLEAN NOT NULL DEFAULT false,
  "createdAt"      TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"      TIMESTAMP NOT NULL DEFAULT now()
);`,
  },
  timesheet_rows: {
    description: 'One row per project (or per Holiday/Idle/Leave category) per week, with hours mapped to monHours..sunHours columns and an optional remark',
    columns: {
      id: { description: 'Primary key' },
      timesheetId: { description: 'FK to weekly_timesheets.id' },
      projectId: { description: 'FK to projects.id' },
      entryType: { description: 'project / holiday / idle / leave' },
      remark: { description: 'Site engineer note for this row (e.g. reason for leave/idle time, work notes)' },
      amount: { description: 'Calculated cost amount (set on approval)' },
      monHours: { description: 'Monday hours' },
      tueHours: { description: 'Tuesday hours' },
      wedHours: { description: 'Wednesday hours' },
      thuHours: { description: 'Thursday hours' },
      friHours: { description: 'Friday hours' },
      satHours: { description: 'Saturday hours' },
      sunHours: { description: 'Sunday hours' },
      isDeleted: { description: 'Soft delete' },
      createdAt: { description: '' },
      updatedAt: { description: '' },
    },
    createSql: `CREATE TABLE timesheet_rows (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "timesheetId" UUID NOT NULL REFERENCES weekly_timesheets(id),
  "projectId"   UUID REFERENCES projects(id),
  "entryType"   VARCHAR NOT NULL DEFAULT 'project',
  "remark"      TEXT NULL,
  "amount"      DECIMAL(12,2) NOT NULL DEFAULT 0,
  "monHours"    DECIMAL(5,2) NOT NULL DEFAULT 0,
  "tueHours"    DECIMAL(5,2) NOT NULL DEFAULT 0,
  "wedHours"    DECIMAL(5,2) NOT NULL DEFAULT 0,
  "thuHours"    DECIMAL(5,2) NOT NULL DEFAULT 0,
  "friHours"    DECIMAL(5,2) NOT NULL DEFAULT 0,
  "satHours"    DECIMAL(5,2) NOT NULL DEFAULT 0,
  "sunHours"    DECIMAL(5,2) NOT NULL DEFAULT 0,
  "isDeleted"   BOOLEAN NOT NULL DEFAULT false,
  "createdAt"   TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"   TIMESTAMP NOT NULL DEFAULT now()
);`,
    alterSql: `ALTER TABLE timesheet_rows
  ADD COLUMN "remark" TEXT NULL;`,
  },
  project_categories: {
    description: 'Admin-editable project category master table',
    columns: {
      id: { description: 'Primary key' },
      name: { description: 'Category name, e.g. Residential, Commercial, Institutional, Infrastructure (unique)' },
      isDeleted: { description: 'Soft delete flag' },
      createdAt: { description: 'Record creation timestamp' },
      updatedAt: { description: 'Record update timestamp' },
    },
    createSql: `CREATE TABLE project_categories (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR NOT NULL UNIQUE,
  "isDeleted" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);`,
  },
  material_requirements: {
    description: 'Material requirement requests raised by site engineers',
    columns: {
      id: { description: 'Primary key' },
      enquiryNo: { description: 'Unique material requirement number' },
      vendorId: { description: 'FK to vendors.id' },
      projectId: { description: 'FK to projects.id' },
      notes: { description: 'Additional notes' },
      items: { description: 'Array of { description, quantity }' },
      status: { description: 'draft / pending / approved / rejected' },
      isDeleted: { description: 'Soft delete flag' },
      createdBy: { description: 'FK to users.id (site engineer who created it)' },
      createdAt: { description: 'Record creation timestamp' },
      updatedAt: { description: 'Record update timestamp' },
    },
    createSql: `CREATE TABLE material_requirements (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "enquiryNo" VARCHAR NOT NULL UNIQUE,
  "vendorId"  UUID NOT NULL REFERENCES vendors(id),
  "projectId" UUID NOT NULL REFERENCES projects(id),
  notes       TEXT,
  items       JSONB NOT NULL DEFAULT '[]',
  status      VARCHAR(50) NOT NULL DEFAULT 'draft',
  "isDeleted" BOOLEAN NOT NULL DEFAULT false,
  "createdBy" UUID REFERENCES users(id),
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);`,
  },
  vendor_quotations: {
    description: 'Vendor quotation bills uploaded by purchase team for material enquiries',
    columns: {
      id: { description: 'Primary key' },
      groupId: { description: 'Groups quotations submitted together as one purchase enquiry (not shown to users)' },
      projectId: { description: 'FK to projects.id' },
      vendorId: { description: 'FK to vendors.id' },
      items: { description: 'Array of { description, quantity }' },
      quotationUrl: { description: 'Uploaded quotation file URL' },
      quotationKey: { description: 'Uploaded quotation file key' },
      status: { description: 'draft / pending / approved / rejected' },
      isDeleted: { description: 'Soft delete flag' },
      createdAt: { description: 'Record creation timestamp' },
      updatedAt: { description: 'Record update timestamp' },
    },
    createSql: `CREATE TABLE vendor_quotations (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "groupId"       UUID NOT NULL,
  "projectId"     UUID NOT NULL REFERENCES projects(id),
  "vendorId"      UUID NOT NULL REFERENCES vendors(id),
  items           JSONB NOT NULL DEFAULT '[]',
  "quotationUrl"  VARCHAR,
  "quotationKey"  VARCHAR,
  status          VARCHAR(50) NOT NULL DEFAULT 'draft',
  "isDeleted"     BOOLEAN NOT NULL DEFAULT false,
  "createdAt"     TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"     TIMESTAMP NOT NULL DEFAULT now()
);`,
  },
  projects: {
    description: 'New classification columns added to the existing projects table',
    columns: {
      id: { description: 'Primary key' },
      name: { description: 'Project name' },
      projectCode: { description: 'Unique project code' },
      description: { description: 'Project description' },
      location: { description: 'Project location' },
      email: { description: 'Contact email' },
      phone1: { description: 'Contact phone 1' },
      phone2: { description: 'Contact phone 2' },
      clientName: { description: 'Client name' },
      status: { description: 'planning / in_progress / on_hold / completed' },
      projectCategoryId: { description: 'FK to project_categories.id' },
      projectNature: { description: 'brownfield / greenfield' },
      jobType: { description: 'contracting / design_build / design' },
      jobStatus: { description: 'bidding / awarded' },
      financialYear: { description: 'e.g. 2026-2027' },
      dateOfCreation: { description: 'Manually set project creation date' },
      completionPct: { description: 'Completion percentage' },
      estimatedBudget: { description: 'Estimated budget' },
      startDate: { description: 'Project start date' },
      endDate: { description: 'Project end date' },
      isDeleted: { description: 'Soft delete flag' },
      createdBy: { description: 'FK to users.id' },
      updatedBy: { description: 'FK to users.id' },
      createdAt: { description: 'Record creation timestamp (system-managed)' },
      updatedAt: { description: 'Record update timestamp' },
    },
    alterSql: `-- If the projects table already has rows, add "projectCode" nullable first,
-- backfill unique values, then apply NOT NULL + UNIQUE.
ALTER TABLE projects
  ADD COLUMN "projectCode"       VARCHAR,
  ADD COLUMN "projectCategoryId" UUID NULL REFERENCES project_categories(id),
  ADD COLUMN "projectNature"     VARCHAR NULL,
  ADD COLUMN "jobType"           VARCHAR NULL,
  ADD COLUMN "jobStatus"         VARCHAR NOT NULL DEFAULT 'bidding',
  ADD COLUMN "financialYear"     VARCHAR NULL,
  ADD COLUMN "dateOfCreation"    DATE NULL;

-- After backfilling projectCode for existing rows:
ALTER TABLE projects
  ALTER COLUMN "projectCode" SET NOT NULL,
  ADD CONSTRAINT uq_projects_project_code UNIQUE ("projectCode");`,
  },
  purchase_orders: {
    description: 'Purchase orders created from approved vendor quotations',
    columns: {
      id: { description: 'Primary key' },
      poNumber: { description: 'Unique PO number (PO-YYYY-NNN)' },
      vendorId: { description: 'FK to vendors.id' },
      projectId: { description: 'FK to projects.id' },
      paymentTerms: { description: 'Payment terms description' },
      status: { description: 'pending / admin_approved / approved / rejected' },
      totalAmount: { description: 'Basic total (sum of item amounts)' },
      gstPercent: { description: 'GST percentage applied' },
      gstAmount: { description: 'Calculated GST amount' },
      totalWithGst: { description: 'Total including GST' },
      billFileUrl: { description: 'Uploaded PO file URL' },
      billFileKey: { description: 'Uploaded PO file key' },
      isDeleted: { description: 'Soft delete flag' },
      createdBy: { description: 'FK to users.id' },
      updatedBy: { description: 'FK to users.id' },
      createdAt: { description: 'Record creation timestamp' },
      updatedAt: { description: 'Record update timestamp' },
    },
    createSql: `CREATE TABLE purchase_orders (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "poNumber"      VARCHAR NOT NULL UNIQUE,
  "vendorId"      UUID NOT NULL REFERENCES vendors(id),
  "projectId"     UUID NOT NULL REFERENCES projects(id),
  "paymentTerms"  TEXT,
  status          VARCHAR(50) NOT NULL DEFAULT 'pending',
  "totalAmount"   DECIMAL(12,2) NOT NULL DEFAULT 0,
  "gstPercent"    DECIMAL(5,2),
  "gstAmount"     DECIMAL(12,2),
  "totalWithGst"  DECIMAL(12,2),
  "billFileUrl"   VARCHAR,
  "billFileKey"   VARCHAR,
  "isDeleted"     BOOLEAN NOT NULL DEFAULT false,
  "createdBy"     UUID REFERENCES users(id),
  "updatedBy"     UUID REFERENCES users(id),
  "createdAt"     TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt"     TIMESTAMP NOT NULL DEFAULT now()
);`,
  },
  po_items: {
    description: 'Line items within a purchase order',
    columns: {
      id: { description: 'Primary key' },
      purchaseOrderId: { description: 'FK to purchase_orders.id (CASCADE delete)' },
      description: { description: 'Item description' },
      quantity: { description: 'Ordered quantity' },
      unit: { description: 'Unit of measure' },
      rate: { description: 'Rate per unit' },
      amount: { description: 'Calculated amount (qty * rate)' },
      billedQuantity: { description: 'Quantity already billed against this item' },
    },
    createSql: `CREATE TABLE po_items (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "purchaseOrderId" UUID NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  description       VARCHAR NOT NULL,
  quantity          DECIMAL(12,3) NOT NULL,
  unit              VARCHAR NOT NULL DEFAULT 'nos',
  rate              DECIMAL(12,2) NOT NULL,
  amount            DECIMAL(12,2) NOT NULL,
  "billedQuantity"  DECIMAL(12,3) NOT NULL DEFAULT 0
);`,
  },
};
